### ISSUE TITLE
Invalid type passed to function

### ISSUE THREAD

**Issue by designbymind** [hansemannn/ti.splashview#1]
Hey Hans,

Thanks for porting this over to Titanium!

Unfortunately, I'm getting an error when trying to implement it. Maybe it's something on my end but using the module seems pretty straightforward, so hopefully you can provide some insight...

**Below is the error I'm getting:**
```
[ERROR] :      column = 9;
[ERROR] :      line = 40;
[ERROR] :      message = "Invalid type passed to function";
[ERROR] :      nativeLocation = "-[TiSplashviewSplashView splashView] (TiSplashviewSplashView.m:21)";
[ERROR] :      nativeReason = "expected: String, was: (null)";
[ERROR] :      sourceURL = xxx/TestProject.app/app.js";
[ERROR] :      stack = "[native code]\nglobal code@file:///xxx/TestProject.app/app.js:40:9";
```

**Below is the code I'm using to test the module (app.js):**
```
var win = Ti.UI.createWindow({
	height : Ti.UI.FILL,
	width : Ti.UI.FILL
});

var TiSplashview = require('ti.splashview');

var splashView = TiSplashview.createSplashView({
	image : "appc-logo.png", //triple-checked this asset/location is valid
	backgroundColor : "blue"
});

win.addEventListener('focus', function(e) {
	setTimeout(function() {
		splashView.startAnimation();
	}, 1000);
});

win.add(splashView);
win.open();
```

Thanks again & let me know if I can provide any additional info or example code!

· Jason

**Comment by hansemannn** [comment]
Sorry, `backgroundColor` was renamed to `fillColor` in the final release, I'll update the readme now!

**Comment by designbymind** [comment]
Awesome, thanks @hansemannn!
`backgroundColor:[[TiUtils colorValue:fillColor] _color]`
